CREATE DATABASE [JobDb] CONTAINMENT = NONE ON PRIMARY (
  NAME = N'JobDb',
  FILENAME = N'G:\DataBases\JobDb.mdf',
  SIZE = 8192KB,
  FILEGROWTH = 65536KB
) LOG ON (
  NAME = N'JobDb_log',
  FILENAME = N'G:\DataBases\JobDb_log.ldf',
  SIZE = 8192KB,
  FILEGROWTH = 65536KB
) COLLATE Persian_100_CI_AS
GO
ALTER DATABASE [JobDb]
SET
  COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [JobDb]
SET
  ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [JobDb]
SET
  ANSI_NULLS OFF
GO
ALTER DATABASE [JobDb]
SET
  ANSI_PADDING OFF
GO
ALTER DATABASE [JobDb]
SET
  ANSI_WARNINGS OFF
GO
ALTER DATABASE [JobDb]
SET
  ARITHABORT OFF
GO
ALTER DATABASE [JobDb]
SET
  AUTO_CLOSE OFF
GO
ALTER DATABASE [JobDb]
SET
  AUTO_SHRINK OFF
GO
ALTER DATABASE [JobDb]
SET
  AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [JobDb]
SET
  AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [JobDb]
SET
  CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [JobDb]
SET
  CURSOR_DEFAULT GLOBAL
GO
ALTER DATABASE [JobDb]
SET
  CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [JobDb]
SET
  NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [JobDb]
SET
  QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [JobDb]
SET
  RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [JobDb]
SET
  DISABLE_BROKER
GO
ALTER DATABASE [JobDb]
SET
  AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [JobDb]
SET
  DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [JobDb]
SET
  PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [JobDb]
SET
  READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [JobDb]
SET
  READ_WRITE
GO
ALTER DATABASE [JobDb]
SET
  RECOVERY FULL
GO
ALTER DATABASE [JobDb]
SET
  MULTI_USER
GO
ALTER DATABASE [JobDb]
SET
  PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [JobDb]
SET
  TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [JobDb]
SET
  DELAYED_DURABILITY = DISABLED
GO
USE [JobDb]
GO
ALTER DATABASE SCOPED CONFIGURATION
SET
  LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY
SET
  LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION
SET
  MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY
SET
  MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION
SET
  PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY
SET
  PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION
SET
  QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY
SET
  QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [JobDb]
GO
IF NOT EXISTS (
    SELECT
  name
FROM sys.filegroups
WHERE
      is_default = 1
  AND name = N'PRIMARY'
  ) ALTER DATABASE [JobDb]
MODIFY
  FILEGROUP [PRIMARY] DEFAULT
GO
USE [JobDb]
GO
/****** Object:  Table [dbo].[JobDetail]    Script Date: 11/5/2019 7:18:57 PM ******/
SET
  ANSI_NULLS ON
GO
SET
  QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[JobDetails]
(
  [Id] [int] NOT NULL,
  [JobId] [int] NOT NULL,
  [Key] [nvarchar](200) NULL,
  [Value] [nvarchar](max) NULL,
  CONSTRAINT [PK_JobDetail] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Jobs]    Script Date: 11/5/2019 7:18:57 PM ******/
SET
  ANSI_NULLS ON
GO
SET
  QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Jobs]
(
  [Id] [int] IDENTITY(1, 1) NOT NULL,
  [Title] [nvarchar](300) NULL,
  [Company] [nvarchar](300) NULL,
  [Place] [nvarchar](300) NULL,
  CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TestTable]    Script Date: 11/5/2019 7:18:57 PM ******/
SET
  ANSI_NULLS ON
GO
SET
  QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TestTable]
(
  [Id] [int] NOT NULL,
  [Name] [nvarchar](50) NULL,
  CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (
      PAD_INDEX = OFF,
      STATISTICS_NORECOMPUTE = OFF,
      IGNORE_DUP_KEY = OFF,
      ALLOW_ROW_LOCKS = ON,
      ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
) ON [PRIMARY]
GO